name: Fetch latest data, commit

on:
  repository_dispatch:
  schedule:
    - cron:  '00 12 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out repo
    - name: Fetch, update and commit sanctions data
      run: . update_and_commit_all.sh
